title: Jekyll any theme
description: Jekyll any theme – Customizable Bootstrap 4

plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-coffeescript

# Defaults
defaults:
  -
    scope:
      path: assets/pages
    values:
      fluid: false
      navbar: bottom
      # theme: basic_light_sans

# theme: basic_light_sans

emptyArray: []

exclude: ["assets/css_no/"]
