title: Jekyll any theme
description: Jekyll any theme – Customizable Bootstrap 4

plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-coffeescript

# Defaults
defaults:
  -
    scope:
      path: assets/pages
    values:
      fluid: false
      navbar: bottom
      # theme: dnd
      # font_face: fonts/scala/fonts.css

emptyArray: []

exclude: ["assets/css_no/"]
